# Generated by Django 5.2 on 2025-08-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/student_images/', verbose_name='صورة الطالب'),
        ),
    ]
