# Generated by Django 5.2 on 2025-07-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_alter_class_options_alter_class_unique_together_and_more'),
        ('subject', '0007_alter_subject_default_weekly_lessons_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('title', models.CharField(help_text='عنوان وصفي للمحتوى (مثال: محاضرة 1، روابط مفيدة، ملخص الفصل الأول).', max_length=255, verbose_name='عنوان المحتوى')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_contents', to='classes.section', verbose_name='القسم')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='subject.subject', verbose_name='المادة الدراسية')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_content', to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'محتوى المادة',
                'verbose_name_plural': 'محتويات المواد',
                'ordering': ['subject', 'section', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('attachment_type', models.CharField(choices=[('text', 'نص'), ('link', 'رابط'), ('file', 'ملف (عام)'), ('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت')], help_text='اختر نوع هذا المرفق: نص، رابط، ملف، صورة، فيديو، أو صوت.', max_length=10, verbose_name='نوع المرفق')),
                ('text_content', models.TextField(blank=True, help_text="اكتب المحتوى النصي إذا كان نوع المرفق 'نص'.", max_length=500, null=True, verbose_name='المحتوى النصي')),
                ('link_url', models.URLField(blank=True, help_text="أدخل رابط URL إذا كان نوع المرفق 'رابط'.", max_length=500, null=True, verbose_name='رابط URL')),
                ('file', models.FileField(blank=True, help_text="رفع ملف إذا كان نوع المرفق 'ملف'، 'صورة'، 'فيديو'، أو 'صوت'.", null=True, upload_to='contents/subject_content_attachments/', verbose_name='ملف المرفق')),
                ('description', models.CharField(blank=True, help_text='وصف قصير للمرفق.', max_length=255, null=True, verbose_name='الوصف')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contents.subjectcontent', verbose_name='محتوى المادة')),
            ],
            options={
                'verbose_name': 'مرفق المحتوى',
                'verbose_name_plural': 'مرفقات المحتوى',
                'ordering': ['content', 'id'],
            },
        ),
    ]
