# Generated by Django 5.2 on 2025-07-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_dayofweek_timeslot'),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcontent',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_contents', to='academic.academicterm', verbose_name='الفصل الدراسي'),
        ),
        migrations.AddField(
            model_name='subjectcontent',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_contents', to='academic.academicyear', verbose_name='العام الدراسي'),
        ),
    ]
