# Generated by Django 5.2 on 2025-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_options_alter_class_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='students_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد الطلاب الحالي'),
        ),
    ]
