# Generated by Django 5.2 on 2025-08-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_section_students_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_class', to='classes.class', verbose_name='الصف التالي'),
        ),
    ]
