# Generated by Django 5.2 on 2025-08-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_timeslot_name'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheravailability',
            name='day_of_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availability', to='academic.dayofweek', verbose_name='يوم الأسبوع'),
        ),
    ]
