# Generated by Django 5.2 on 2025-08-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_dayofweek_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='name',
            field=models.CharField(default=1, help_text="اسم تعريفي للفترة (مثال: 'الحصة الأولى', 'الاستراحة الأولى')", max_length=50, verbose_name='اسم الحصة'),
            preserve_default=False,
        ),
    ]
