# Generated by Django 5.2 on 2025-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsactivity',
            name='target_audience',
            field=models.CharField(choices=[('all', 'الجميع'), ('teachers', 'المعلمون'), ('students', 'الطلاب'), ('class', 'فصل دراسي'), ('section', 'قسم'), ('subject', 'مادة دراسية')], default='all', max_length=20, verbose_name='الجمهور المستهدف'),
        ),
    ]
