# Generated by Django 5.2 on 2025-08-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0004_timeslot_name'),
        ('classes', '0004_class_next_class'),
        ('students', '0008_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='المعدل العام')),
                ('result_status', models.CharField(choices=[('promoted', 'ناجح'), ('failed', 'راسب'), ('graduated', 'متخرج')], max_length=20, verbose_name='حالة النتيجة')),
                ('is_promoted', models.BooleanField(default=False, help_text='يشير إلى ما إذا كان الطالب قد تم ترقيته إلى صف أعلى.', verbose_name='هل تم ترقيته؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progressions', to='academic.academicyear', verbose_name='العام الدراسي')),
                ('from_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_from', to='classes.class', verbose_name='من الصف')),
                ('from_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_from', to='classes.section', verbose_name='من الشعبة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_records', to='students.student', verbose_name='الطالب')),
                ('to_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_to', to='classes.class', verbose_name='إلى الصف')),
                ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_to', to='classes.section', verbose_name='إلى الشعبة')),
            ],
            options={
                'verbose_name': 'تقدم الطالب',
                'verbose_name_plural': 'سجلات تقدم الطلاب',
                'ordering': ['-academic_year__start_date', 'student__user__first_name'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentProgressionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('issue_type', models.CharField(choices=[('section_capacity_full', 'سعة الشعبة ممتلئة'), ('no_available_section', 'لا توجد شعبة متاحة'), ('inactive_section', 'الشعبة غير نشطة')], max_length=50, verbose_name='نوع المشكلة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل؟')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('student_progression', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='progression.studentprogression', verbose_name='سجل التقدم')),
            ],
            options={
                'verbose_name': 'مشكلة تقدم طالب',
                'verbose_name_plural': 'مشاكل تقدم الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
