# Generated by Django 5.2 on 2025-08-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_conducted',
            field=models.BooleanField(default=False, help_text='يشير إلى ما إذا كان الاختبار قد تم إجراؤه بالفعل.', verbose_name='هل تم إجراء الاختبار؟'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='المعلم المسؤول عن هذا الاختبار.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to='teachers.teacher', verbose_name='المعلم المسؤول'),
        ),
    ]
