# Generated by Django 5.2 on 2025-08-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_exam_is_conducted_exam_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='stream_type',
            field=models.CharField(blank=True, choices=[('General', 'عام'), ('Scientific', 'علمي'), ('Literary', 'أدبي')], help_text='نوع التخصص المستهدف (مثال: علمي، أدبي) ضمن الصف المحدد.', max_length=20, null=True, verbose_name='نوع التخصص'),
        ),
    ]
