# Generated by Django 5.2 on 2025-08-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_alter_exam_stream_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['student__user__last_name'], 'verbose_name': 'درجة', 'verbose_name_plural': 'الدرجات'},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='out_of',
        ),
    ]
