# Generated by Django 5.2 on 2025-08-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المدرسة')),
                ('school_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف المدرسة')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/logo/', verbose_name='شعار المدرسة')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('school_type', models.CharField(blank=True, choices=[('Primary', 'ابتدائي'), ('Middle', 'إعدادي'), ('Secondary', 'ثانوي')], max_length=20, null=True, verbose_name='نوع المدرسة')),
                ('school_status', models.CharField(blank=True, choices=[('Public', 'حكومي'), ('Private', 'خاصة')], max_length=20, null=True, verbose_name='حالة المدرسة')),
                ('student_registration', models.BooleanField(default=False, verbose_name='تسجيل الطلاب متاح؟')),
            ],
            options={
                'verbose_name': 'ملف المدرسة',
                'verbose_name_plural': 'ملف المدرسة',
            },
        ),
    ]
