# Generated by Django 5.2 on 2025-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='student_registration',
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='schoolProfile/logo/', verbose_name='شعار المدرسة'),
        ),
    ]
