# Generated by Django 5.2.3 on 2025-07-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_remove_sectionsubjectrequirement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.AddField(
            model_name='subject',
            name='weekly_sessions',
            field=models.IntegerField(default=0, help_text='عدد الحصص المخصصة لهذه المادة أسبوعياً.', verbose_name='عدد الحصص الأسبوعية'),
        ),
    ]
