# Generated by Django 5.2.3 on 2025-07-01 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_options_alter_class_unique_together_and_more'),
        ('subject', '0004_remove_subject_section_subject_weekly_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='weekly_sessions',
        ),
        migrations.AddField(
            model_name='subject',
            name='default_weekly_lessons',
            field=models.PositiveIntegerField(default=0, help_text='عدد الحصص الأسبوعية الافتراضي لهذه المادة، يستخدم عند عدم تحديد عدد معين للشعبة.', verbose_name='عدد الحصص الأسبوعية الافتراضي'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='رفع ملف المنهج الدراسي أو مواد مساعدة بصيغة PDF.', null=True, upload_to='subject_pdfs/', verbose_name='ملف المنهج الدراسي PDF'),
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(blank=True, help_text='القسم الذي تنتمي إليه هذه المادة (مثال: القسم أ).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_in_section', to='classes.section', verbose_name=' الشعبة'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('class_obj', 'stream_type', 'name'), name='unique_subject_per_class_and_stream'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('class_obj__isnull', True), ('stream_type__isnull', True)), fields=('section', 'name'), name='unique_subject_per_section'),
        ),
    ]
