# Generated by Django 5.2.3 on 2025-07-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_remove_subject_pdf_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='رفع ملف المنهج الدراسي أو مواد مساعدة بصيغة PDF.', null=True, upload_to='subject/media/subject_pdfs/', verbose_name='ملف المنهج الدراسي PDF'),
        ),
    ]
