# Generated by Django 5.2 on 2025-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_alter_subject_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='default_weekly_lessons',
            field=models.PositiveIntegerField(default=1, help_text='عدد الحصص الأسبوعية الافتراضي لهذه المادة، يستخدم عند عدم تحديد عدد معين للشعبة.', verbose_name='عدد الحصص الأسبوعية الافتراضي'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='رفع ملف المنهج الدراسي أو مواد مساعدة بصيغة PDF.', null=True, upload_to='subject_pdfs/', verbose_name='ملف المنهج الدراسي PDF'),
        ),
    ]
