# Generated by Django 5.2 on 2025-08-14 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_alter_subject_default_weekly_lessons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الأيقونة')),
                ('icon_file', models.ImageField(help_text='تحميل ملف الأيقونة كصورة (يفضل صيغة SVG أو PNG).', upload_to='subject/subject_files/icons/', verbose_name='ملف الأيقونة')),
            ],
            options={
                'verbose_name': 'أيقونة المادة',
                'verbose_name_plural': 'أيقونات المواد',
            },
        ),
        migrations.AlterField(
            model_name='subject',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='رفع ملف المنهج الدراسي أو مواد مساعدة بصيغة PDF.', null=True, upload_to='subject/subject_files/subject_pdfs/', verbose_name='ملف المنهج الدراسي PDF'),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_with_icon', to='subject.subjecticon', verbose_name='أيقونة المادة'),
        ),
    ]
