# Generated by Django 5.2 on 2025-08-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_timeslot_name'),
        ('classes', '0003_section_students_count'),
        ('subject', '0009_subjecticon_alter_subject_pdf_file_subject_icon'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_per_class_and_stream',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_per_section',
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_in_term', to='academic.academicterm', verbose_name='الفصل الدراسي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_in_year', to='academic.academicyear', verbose_name='العام الدراسي'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('class_obj', 'stream_type', 'name', 'academic_year', 'academic_term'), name='unique_subject_per_class_and_stream_term'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('class_obj__isnull', True), ('stream_type__isnull', True)), fields=('section', 'name', 'academic_year', 'academic_term'), name='unique_subject_per_section_term'),
        ),
    ]
