# Generated by Django 5.2 on 2025-08-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_timeslot_name'),
        ('attendance', '0001_initial'),
        ('students', '0008_alter_student_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='academic.academicterm', verbose_name='الفصل الدراسي'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='academic.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'معذور')], default='present', help_text='حالة حضور الطالب: حاضر، غائب، متأخر، معذور.', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'academic_term', 'academic_year')},
        ),
    ]
