# Generated by Django 5.2 on 2025-08-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'معذور')], default='present', help_text='حالة حضور الطالب: حاضر، غائب، متأخر، معذور.', max_length=10, verbose_name='الحالة'),
        ),
    ]
